version: "3.9"
services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./vectorstore:/app/vectorstore
      - ./docs:/app/docs
    restart: unless-stopped 